DROP TABLE IF EXISTS customer CASCADE;

CREATE TABLE IF NOT EXISTS customer(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    type VARCHAR(10) NOT NULL,
    person_id INT REFERENCES person(id) NOT NULL ON DELETE CASCADE
);